import { Router } from 'express';
import authRoutes from './authRoutes';
import studentRoutes from './studentRoutes';
import newsRoutes from './newsRoutes';
import eventRoutes from './eventRoutes';
import dashboardRoutes from './dashboardRoutes';
import programRoutes from './programRoutes';
import achievementRoutes from './achievementRoutes';
import faqRoutes from './faqRoutes';
import resourceRoutes from './resourceRoutes';
import settingRoutes from './settingRoutes';
import contactRoutes from './contactRoutes';
import volunteerRoutes from './volunteerRoutes';
import galleryRoutes from './galleryRoutes';
import tickerRoutes from './tickerRoutes';
import translationRoutes from './translationRoutes';
import mediaRoutes from './mediaRoutes';
import uploadRoutes from './uploadRoutes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/students', studentRoutes);
router.use('/news', newsRoutes);
router.use('/events', eventRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/programs', programRoutes);
router.use('/achievements', achievementRoutes);
router.use('/faq', faqRoutes);
router.use('/resources', resourceRoutes);
router.use('/settings', settingRoutes);
router.use('/contacts', contactRoutes);
router.use('/volunteers', volunteerRoutes);
router.use('/gallery', galleryRoutes);
router.use('/ticker', tickerRoutes);
router.use('/translations', translationRoutes);
router.use('/media', mediaRoutes);
router.use('/upload', uploadRoutes);

export default router;
